development:
 adapter: postgresql
 encoding: unicode
 database: hipstagram_dev
 host: localhost
 pool: 5
 username: ENV['DB_USER']
 password: ENV['DB_PASS']

test:
 adapter: postgresql
 encoding: unicode
 database: hipstagram_test
 host: localhost
 pool: 5
 username: ENV['DB_USER']
 password: ENV['DB_PASS']